### ISSUE TITLE
Unable to upgrade Gitea from version 1.12.4 using docker on Raspberry Pi 3B

### ISSUE THREAD

**Issue by gcoter** [watson81/docker-gitea-rpi#3]
Hello :slightly_smiling_face: 

I have been using your image for several years now on a Raspberry Pi at home. I realized that I should upgrade it (yeah, I admit that I have not done regularly :sweat_smile:) and I got some trouble.

For more details, you can refer to this issue that I opened on the Gitea repo (initially, I did not find this repo so I reached out to them): https://github.com/go-gitea/gitea/issues/32202

In a nutshell, this table summarizes the versions I tried and the error I got:

| Version | Error |
| ---------- | ------- |
| 1.22.2 | Command not found: /usr/bin/entrypoint |
| 1.16.0 | Command not found: /usr/bin/entrypoint |
| 1.15.11 | Command not found: /usr/bin/entrypoint |
| 1.14.7 | Command not found: /usr/bin/entrypoint |
| 1.13.7 | Infinite warnings like "s6-supervise openssh: warning: can't happen: timeout while the service is up!" |

Can you help me? Is this repo still actively maintained?

**Comment by watson81** [comment]
@gcoter Yes, I still maintain this repo. There's just been no need to update the source code in a very long time since it's essentially a build process rather than truely active code. I.e. I just have to kick off builds that reference the newest packages released by the Gitea team.

Can you please tell me the exact command line that you're using to start the container and what docker version you're  running?

**Comment by gcoter** [comment]
Hi @watson81, thank you for your response :slightly_smiling_face: 

I am using the following docker compose config:
```
version: "2"

volumes:
  data:
    driver: local

services:
  server:
    image: patrickthedev/gitea-rpi:1.12.4
    mem_limit: 150m
    memswap_limit: 150m
    hostname: <HOSTNAME>
    environment:
      - RUN_MODE=prod
      - SSH_DOMAIN=<HOSTNAME>
      - SSH_PORT=<SSH_PORT>
      - SSH_LISTEN_PORT=22
    networks:
      - web
    ports:
      - "9090:3000"
      - "<SSH_PORT>:22"
    labels:
      - traefik.enable=true
      - traefik.frontend.rule=Host:<HOSTNAME>
      - traefik.http.services.gitea.loadbalancer.server.port=3000
      - traefik.port=3000
      - traefik.docker.network=web
    volumes:
      - data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

networks:
  web:
    external: true
```

With `Docker version 19.03.15, build 99e3ed8919` and `docker-compose version 1.24.1, build 4667896` on a Raspberry Pi 3B (`Raspbian GNU/Linux 9 (stretch)`)

Don't hesitate if you need more information!
